### ISSUE TITLE
Accept From Notification

### ISSUE THREAD

**Issue by maheshbhattaraai** [ConnectyCube/connectycube-flutter-samples#122]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[*] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[* ] Android
[ ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
```
E/flutter ( 9155): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter ( 9155): At this point the state of the widget's element tree is no longer stable.
E/flutter ( 9155): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter ( 9155): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3944:9)
E/flutter ( 9155): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3958:6)
E/flutter ( 9155): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:4005:12)
E/flutter ( 9155): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:2727:40)
E/flutter ( 9155): #4      CallManager.acceptCall (package:vabisya/managers/call_manager.dart:142:19)
E/flutter ( 9155): #5      CallManager._initCalls.<anonymous closure> (package:vabisya/managers/call_manager.dart:82:9)
E/flutter ( 9155): <asynchronous suspension>
```
The first call from notification will receive and goes to conversation screen and after the first call then accept from notification product the above error.

**Comment by TatankaConCube** [comment]
Could you please attach the full log from the flutter console here?

**Comment by maheshbhattaraai** [comment]
Some time this issue occurs when a call is accepted but did not go to the conversation screen. The issue occurs in the navigator. of(context). Somehow can we show incoming call dialog like messenger and ringtone is played for a notification time too short? How can we elongate ringtone duration.
