### ISSUE TITLE
roomId = Uuid().v4() can't join Conference Call 

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#148]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[x ] Conference Call sample

I create Call Session with roomId = Uuid().v4() =>i can't join Conference Call

**Comment by TatankaConCube** [comment]
> can't join Conference Call

what does it mean? Do you have any errors here? Please fill all fields required by our templates on the ticket creation step.

**Comment by beheobong** [comment]
And log errror:
```
flutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.error, sessionId=null}
flutter: CB-SDK: PushNotificationsManager: onError Instance of 'WsException'
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'WsError' is not a subtype of type 'FutureOr<WsDataPacket>?' of 'value'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart)
#1      PacketCollector.processPacket (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:150:18)
#2      WebSocketConnection.processResponse.<anonymous closure> (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:109:49)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      WebSocketConnection.processResponse (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:109:16)
#5      WebSocketConnection.notifyListeners (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:105:5)
#6      WebSocketConnection.onParseMessage (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:91:5)
#7      WebSocketConnection.connect.<anonymous closure> (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:41:7)
#8      _rootRunUnary (dart:async/zone.dart:1362:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#14     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#16     _rootRunUnary (dart:async/zone.dart:1362:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#22     _StreamController._add (dart:async/stream_controller.dart:607:7)
#23     _rootRunUnary (dart:async/zone.dart:1362:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#29     _StreamController._add (dart:async/stream_controller.dart:607:7)
#30     _StreamController.add (dart:async/stream_controller.dart:554:5)
#31     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#32     _rootRunUnary (dart:async/zone.dart:1362:47)
#33     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#42     _rootRunUnary (dart:async/zone.dart:1362:47)
#43     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#48     _StreamController._add (dart:async/stream_controller.dart:607:7)
#49     _StreamController.add (dart:async/stream_controller.dart:554:5)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#51     _rootRunUnary (dart:async/zone.dart:1362:47)
#52     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#57     _StreamController._add (dart:async/stream_controller.dart:607:7)
#58     _StreamController.add (dart:async/stream_controller.dart:554:5)
#59     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#60     _rootRun (dart:async/zone.dart:1346:47)
#61     _CustomZone.run (dart:async/zone.dart:1258:19)
#62     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#63     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#64     _rootRun (dart:async/zone.dart:1354:13)
#65     _CustomZone.run (dart:async/zone.dart:1258:19)
#66     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#67     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#68     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#69     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: 2021-10-06T10:54:43.383033: CB-SDK: : RCV(3): {
flutter:    "janus": "success",
flutter:    "session_id": 6753870827752846,
flutter:    "transaction": "ef62355f-9cb0-4629-9c55-5e3eb3691014",
flutter:    "data": {
flutter:       "id": 4497348399177828
flutter:    }
flutter: }
flutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=6753870827752846}
flutter: 2021-10-06T10:54:43.385759: CB-SDK: JanusSignaler: attachPlugin wsDataPacket= WsPacket{messageType=Type.success, sessionId=6753870827752846}
flutter: 2021-10-06T10:54:43.386569: CB-SDK: JanusSignaler: startAutoSendPresence
flutter: 2021-10-06T10:54:43.387503: CB-SDK: : SND(3): {"janus":"message","session_id":6753870827752846,"transaction":"74259260-b242-4ade-9821-0f23b4c8b48f","token":null,"handle_id":4497348399177828,"body":{"id":4729548,"feed":null,"ptype":"publisher","room":"227376e0-2659-11ec-83a6-4d0f7755a143","request":"join"}}
flutter: 2021-10-06T10:54:43.390464: CB-SDK: : RCV(3): {
flutter:    "janus": "error",
flutter:    "session_id": 6753870827752846,
flutter:    "transaction": "73a4d989-db19-4ab2-8ba6-cacc0ac11f25",
flutter:    "error": {
flutter:       "code": 459,
flutter:       "reason": "No such handle 6753870827752846 in session 6753870827752846"
flutter:    }
flutter: }
flutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.error, sessionId=6753870827752846}
flutter: CB-SDK: PushNotificationsManager: onError Instance of 'WsException'
flutter: CallKitManager, endCallflutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.error, sessionId=null}
flutter: CB-SDK: PushNotificationsManager: onError Instance of 'WsException'
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'WsError' is not a subtype of type 'FutureOr<WsDataPacket>?' of 'value'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart)
#1      PacketCollector.processPacket (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:150:18)
#2      WebSocketConnection.processResponse.<anonymous closure> (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:109:49)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      WebSocketConnection.processResponse (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:109:16)
#5      WebSocketConnection.notifyListeners (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:105:5)
#6      WebSocketConnection.onParseMessage (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:91:5)
#7      WebSocketConnection.connect.<anonymous closure> (package:connectycube_sdk/src/calls/signaling/web_socket_connection.dart:41:7)
#8      _rootRunUnary (dart:async/zone.dart:1362:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#14     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#16     _rootRunUnary (dart:async/zone.dart:1362:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#22     _StreamController._add (dart:async/stream_controller.dart:607:7)
#23     _rootRunUnary (dart:async/zone.dart:1362:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#29     _StreamController._add (dart:async/stream_controller.dart:607:7)
#30     _StreamController.add (dart:async/stream_controller.dart:554:5)
#31     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#32     _rootRunUnary (dart:async/zone.dart:1362:47)
#33     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#42     _rootRunUnary (dart:async/zone.dart:1362:47)
#43     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#48     _StreamController._add (dart:async/stream_controller.dart:607:7)
#49     _StreamController.add (dart:async/stream_controller.dart:554:5)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#51     _rootRunUnary (dart:async/zone.dart:1362:47)
#52     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#57     _StreamController._add (dart:async/stream_controller.dart:607:7)
#58     _StreamController.add (dart:async/stream_controller.dart:554:5)
#59     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#60     _rootRun (dart:async/zone.dart:1346:47)
#61     _CustomZone.run (dart:async/zone.dart:1258:19)
#62     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#63     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#64     _rootRun (dart:async/zone.dart:1354:13)
#65     _CustomZone.run (dart:async/zone.dart:1258:19)
#66     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#67     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#68     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#69     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: 2021-10-06T10:54:43.383033: CB-SDK: : RCV(3): {
flutter:    "janus": "success",
flutter:    "session_id": 6753870827752846,
flutter:    "transaction": "ef62355f-9cb0-4629-9c55-5e3eb3691014",
flutter:    "data": {
flutter:       "id": 4497348399177828
flutter:    }
flutter: }
flutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=6753870827752846}
flutter: 2021-10-06T10:54:43.385759: CB-SDK: JanusSignaler: attachPlugin wsDataPacket= WsPacket{messageType=Type.success, sessionId=6753870827752846}
flutter: 2021-10-06T10:54:43.386569: CB-SDK: JanusSignaler: startAutoSendPresence
flutter: 2021-10-06T10:54:43.387503: CB-SDK: : SND(3): {"janus":"message","session_id":6753870827752846,"transaction":"74259260-b242-4ade-9821-0f23b4c8b48f","token":null,"handle_id":4497348399177828,"body":{"id":4729548,"feed":null,"ptype":"publisher","room":"227376e0-2659-11ec-83a6-4d0f7755a143","request":"join"}}
flutter: 2021-10-06T10:54:43.390464: CB-SDK: : RCV(3): {
flutter:    "janus": "error",
flutter:    "session_id": 6753870827752846,
flutter:    "transaction": "73a4d989-db19-4ab2-8ba6-cacc0ac11f25",
flutter:    "error": {
flutter:       "code": 459,
flutter:       "reason": "No such handle 6753870827752846 in session 6753870827752846"
flutter:    }
flutter: }
flutter: CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.error, sessionId=6753870827752846}
flutter: CB-SDK: PushNotificationsManager: onError Instance of 'WsException'
```
