### ISSUE TITLE
PushNotificationsManager bug in P2P Call Sample

### ISSUE THREAD

**Issue by chaghen** [ConnectyCube/connectycube-flutter-samples#174]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[] P2P Call sample
 MethodChannelFirebaseMessaging.requestPermission (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:286:13)
E/flutter (26991): <asynchronous suspension>
E/flutter (26991): #2      PushNotificationsManager._initFcm (package:p2p_call_sample/src/managers/push_notifications_manager.dart:77:5)
[] Conference Call sample

**Platform (use [x])**
[] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by chaghen** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method Messaging#requestPermission on channel plugins.flutter.io/firebase_messaging)        
E/flutter (26991): #0      convertPlatformException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:13:5)

**Comment by TatankaConCube** [comment]
Do you have any issues with sample work? Or you just can see it in logs?

**Comment by TatankaConCube** [comment]
no activity for a long time, so closing
