### ISSUE TITLE
iOS Build Error; WebRTC apparently not found

### ISSUE THREAD

**Issue by benz93chung** [ConnectyCube/connectycube-flutter-samples#183]
This issue (#160) has recurred since 2.0.7, and has since persisted up to 2.0.9 which is the latest version as of the time of creating this issue.

**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Apple
Model: iOS Simulator
OS version: iOS 15

**Describe the bug:**
An error has occurred upon building for iOS. WebRTC is also said to be not found. The workaround of setting "Build Active Architecture Only" to "Yes" onto `Pods` and `flutter_webrtc` in XCode also did not make a difference.

**Steps to Reproduce:**
1. Clone the sample
2. Update SDK to 2.0.9. Also update the Firebase dependencies
3. Build and run

**Logs:**
```
Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Flutter
      - connectivity_plus
      - device_info
      - file_picker
      - firebase_core
      - firebase_messaging
      - flutter_local_notifications
      - flutter_webrtc
      - fluttertoast
      - path_provider
      - platform_device_id
      - shared_preferences
      - sqflite
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '8.10.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    firebase_messaging: Using Firebase SDK version '8.10.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_webrtc` from `.symlinks/plugins/flutter_webrtc/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `platform_device_id` from `.symlinks/plugins/platform_device_id/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_6_1.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.10.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_0.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/1/0/Toast/4.0.0/Toast.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_7_8.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_3_4_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/3/4/4/WebRTC-SDK/92.4515.11/WebRTC-SDK.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.10.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
      In snapshot (Podfile.lock):
        Firebase/Messaging (= 8.9.0)
      In Podfile:
        firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 11.2.5, which depends on
          Firebase/Messaging (= 8.10.0)
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `Firebase/Messaging` inside your development pod `firebase_messaging`.
       You should run `pod update Firebase/Messaging` to apply changes you've made.
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/opt/flutter/bin/cache in PATH, mode 040777
    [!] Automatically assigning platform `iOS` with version `10.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update
Error running pod install
Error launching application on iPhone 13 Pro Max.
Exited (sigterm)
```

**Actual result:**
<img width="941" alt="Screenshot 2022-01-10 at 11 49 36 AM" src="https://user-images.githubusercontent.com/48185630/148716875-99e06540-a1f1-494d-b0d0-233cccc3f510.png">

<img width="1169" alt="Screenshot 2022-01-10 at 11 54 12 AM" src="https://user-images.githubusercontent.com/48185630/148716901-50362ad0-88f5-49da-a848-05a2580893f3.png">

<img width="1167" alt="Screenshot 2022-01-10 at 11 55 57 AM" src="https://user-images.githubusercontent.com/48185630/148716909-014abd5b-6a53-4b92-ad8a-4c6479ccd83d.png">

**Expected behavior:**
 Build should have been successful, and app would have been running on simulator/device.

**Additional info**
N/A

**Comment by TatankaConCube** [comment]
@benz93chung hm, it is strange because on our side it works well

try to move to the root project directory and perform the next commands:
```bash
flutter clean
flutter pub get
cd ios
pod update
```
then open your project in the Xcode and try to build the Archive

**Comment by benz93chung** [comment]
So I revisited this issue again with an actual iOS device at hand. There is no problem building and running the sample with it.

Whereas for running on iOS simulator, the issue revolves around WebRTC and the iOS Simulator architecture. [This workaround](https://github.com/flutter-webrtc/flutter-webrtc/issues/755#issuecomment-960995456) around the `PodFile` did it for me.

You may consider adding this to the `README`. Otherwise, thank you! Closing this issue.
