### ISSUE TITLE
ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#303]
ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT
 ENABLE FCM "NOTIFICATION" PUSH TYPE FOR ANDROID

hi @TatankaConCube , can u provide me breif about this checkboxs and if i send message from chat and have not selected this chechbox can i still get notification ? 

you guys are using firebase fcm only for connectycybe notification righT?

**Comment by richanshah** [comment]
if i dont handle notification from my side just have done subscription then how it will work ?

**Comment by TatankaConCube** [comment]
> ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT

means to enable push notifications if a user is offline and receives a new chat message

> ENABLE FCM "NOTIFICATION" PUSH TYPE FOR ANDROID

means to enable the 'Notification' type of the FCM for the chat push notifications. please follow the Firebase documentation about the differences between the 'Notification' and 'Data' types of FCM push notifications https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

> you guys are using firebase fcm only for connectycybe notification righT?

no, the Connectycube platform supports the FCM, APNS, and APNS_VOIP push notifications

> if i dont handle notification from my side just have done subscription then how it will work ?

if you want to delegate to the system the shoving of the notifications, you need to tick the `ENABLE FCM "NOTIFICATION" PUSH TYPE FOR ANDROID` config

**Comment by richanshah** [comment]
ok , i have enabled this option and successfully subscribed to channel from flutter and waiting for message in onMessageReceived in android native service , but when i send the chat message i am not getting messages. 

although if i send from admin panel then i am gettting the notification . i am not able to find out the issue

**Comment by richanshah** [comment]
@TatankaConCube  , now i am getting from chatting but getting this crash and i researched but didnt find any solution , can u help ? 

sendNotificationDataToFlutterSide: intent data = Bundle[{google.delivered_priority=high, message_id=6501ca00f7a887a5defc1457, google.sent_time=1694616065125, google.ttl=2419200, google.original_priority=high, extension={"message":"hello"}, user_id=10551474, from=425699151479, dialog_type=3, badge=3, sound=default, title=Richa Shah, locData={}, google.message_id=0:1694616065171371%a0a0f185a0a0f185, message=Richa Shah: hello, gcm.n.analytics_data=Bundle[mParcelledData.dataSize=100], dialog_id=64fb1f10bc7b59002f7ea144, ios_thread_id=64fb1f10bc7b59002f7ea144, collapse_key=com.bv.mainCourt}]
20:11:13.163 AndroidRuntime                                               D  Shutting down VM
--------- beginning of crash
20:11:13.181                                                              E  FATAL EXCEPTION: main
                                                                             Process: com.bv.mainCourt, PID: 24377
                                                                             java.lang.IllegalArgumentException: Unsupported value: 'Bundle[mParcelledData.dataSize=100]' of type 'class android.os.Bundle'
                                                                             	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
                                                                             	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
                                                                             	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
                                                                             	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
                                                                             	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
                                                                             	at com.bv.mainCourt.MainActivity.sendNotificationDataToFlutterSide(MainActivity.kt:94)
                                                                             	at com.bv.mainCourt.MainActivity.onNewIntent(MainActivity.kt:47)
                                                                             	at android.app.Activity.performNewIntent(Activity.java:8321)
                                                                             	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1517)
                                                                             	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1530)
                                                                             	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3822)
                                                                             	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3829)
                                                                             	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
                                                                             	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                             	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                             	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                             	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                             	at android.os.Looper.loopOnce(Looper.java:201)
                                                                             	at android.os.Looper.loop(Looper.java:288)
                                                                             	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
