### ISSUE TITLE
invocation:_InvocationMirror called on createsession()

### ISSUE THREAD

**Issue by Bharavi26** [ConnectyCube/connectycube-flutter-samples#55]
![conn](https://user-images.githubusercontent.com/36761436/103059666-c58d9500-45cb-11eb-973c-b45c1e0c664e.png)
**Specify the sample to which the issue belongs (use [x]):**
[ ] P2P Call sample

**Platform (use [x])**
[ ] Flutter

**Describe the bug:**
**await createSession(loginUser);** generating error in background
because of this not able to get currentuser from CubeChatConnection.instance.currentUser its returning null

**Comment by TatankaConCube** [comment]
can you reproduce the same issue on our sample? if 'yes', please specify steps to reproduce, it will help us to localize the problem

**Comment by Bharavi26** [comment]
![conn1](https://user-images.githubusercontent.com/36761436/103064054-04761780-45d9-11eb-96b0-f841ac16859f.png)
![conn](https://user-images.githubusercontent.com/36761436/103064057-063fdb00-45d9-11eb-9cfb-55891cf83f2e.png)

@TatankaConCube sir thank you for response...
i tried manually to get user which is in concube database, suddenly not able to get that user...
createsession also working fine before 2-3 days...suddenly its generating err , when i debug then err goes to **_InvocationMirror**

**Comment by TatankaConCube** [comment]
hello @Bharavi26, little request - please share code and logs in a text format instead of pictures.
About your issue - from your logs, I not completely understand which request do you do, please, share full logs with requests and responses, it will help us to understand which API you call and why you get errors.
Error 'Unauthorized' means that you try to create a session or do sign in with the wrong user data (e-mail or login and password) please, recheck this part of your code.

**Comment by Bharavi26** [comment]
` static LoginToCC(BuildContext context) async {
    CubeSession ccsession;
    print("==loginprocess");
    if (CubeSessionManager.instance.isActiveSessionValid()) {
      print("==loginprocess->1");
      var user = CubeSessionManager.instance.activeSession.user;
      print("==loginprocess->1.1 -> ${user.id}");
      await LoginToCubeChat(context, user);
    } else {
      print("==loginprocess->2");
      ccsession = await createSession();
      print("==loginprocess->2***");
      CubeUser checkUserExist = await GetCubeUserByLogin();
      print("==loginprocess->2.3 ->${checkUserExist == null}");
      if (checkUserExist == null) {
        checkUserExist = await RegisterToCC();
        print("==loginprocess->2.7");
      }
      print("==loginprocess->2.8");


      if(ccsession == null) {
        await createSession(checkUserExist).then((cubeSession) async {
          print("==loginprocess->2.9");
          await LoginToCubeChat(context, checkUserExist);
        }).catchError((error) {
          print("==loginprocess->2.10==${error.toString()}");
        });
      }else {
        print("==loginprocess->2.11==${checkUserExist.password}");
        if(checkUserExist.password == null || checkUserExist.password.trim().isEmpty)
          checkUserExist.password = Constant.ConnectyCube_DEFAULT_PASS;

        await signIn(checkUserExist);
        print("==loginprocess->2.12==");
        await LoginToCubeChat(context, checkUserExist);
      }
    }
  }`

I/flutter (27680): ==loginprocess
I/flutter (27680): ==loginprocess->1
E/flutter (27680): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'id' was called on null.
E/flutter (27680): Receiver: null
E/flutter (27680): Tried calling: id

** var user = CubeSessionManager.instance.activeSession.user;**
activesession returning null user

 if (CubeSessionManager.instance.isActiveSessionValid()) {
      print("==loginprocess->1");
      var user = CubeSessionManager.instance.activeSession.user;
      print("==loginprocess->1.1 -> ${user.id}");
      await LoginToCubeChat(context, user);
    }

**Comment by Bharavi26** [comment]
**sometimes this type of err also gen**

`[log] <stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>
[log] D/[ConnectionNegotiatorManager]: Negotiating features
E/flutter (32713): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s)
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
E/flutter (32713): #0      _StringBase.+ (dart:core-patch/string_patch.dart:267:57)
E/flutter (32713): #1      PlainSaslHandler.sendPlainAuthMessage (package:xmpp_stone/src/features/sasl/PlainSaslHandler.dart:42:57)
E/flutter (32713): #2      PlainSaslHandler.start (package:xmpp_stone/src/features/sasl/PlainSaslHandler.dart:25:5)
E/flutter (32713): #3      SaslAuthenticationFeature._process (package:xmpp_stone/src/features/sasl/SaslAuthenticationFeature.dart:64:19)
E/flutter (32713): #4      SaslAuthenticationFeature.negotiate (package:xmpp_stone/src/features/sasl/SaslAuthenticationFeature.dart:38:7)
E/flutter (32713): #5      ConnectionNegotiatorManager.negotiateNextFeature (package:xmpp_stone/src/features/ConnectionNegotatiorManager.dart:83:24)
E/flutter (32713): #6      ConnectionNegotiatorManager.negotiateFeatureList (package:xmpp_stone/src/features/ConnectionNegotatiorManager.dart:65:5)
E/flutter (32713): #7      Connection.handleResponse.<anonymous closure> (package:xmpp_stone/src/Connection.dart:311:43)
E/flutter (32713): #8      Iterable.forEach (dart:core/iterable.dart:283:30)
E/flutter (32713): #9      Connection.handleResponse (package:xmpp_stone/src/Connection.dart:310:12)
E/flutter (32713): #10     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32713): #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32713): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32713): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32713): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (32713): #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (32713): #16     _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
E/flutter (32713): #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (32713): #18     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32713): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32713): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32713): #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32713): #22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (32713): #23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter (32713): #24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (32713): #25     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
E/flutter (32713): #26     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
E/flutter (32713): #27     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
E/flutter (32713): #28     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
E/flutter (32713): #29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
E/flutter (32713): #30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter (32713): #31     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32713): #32     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32713): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32713): #34     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter (32713): #35     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32713): #36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32713): #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32713): #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32713): #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (32713): #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (32713): #41     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (32713): #42     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter (32713): #43     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
E/flutter (32713): #44     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32713): #45     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32713): #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32713): #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32713): #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (32713): #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (32713): #50     _StreamController._add (dart:async/str
I/flutter (32713): CacheManager: Failed to download file from http://sinel.kasemorgh.com/upload/Banner/top/1603738836198.jpg with error:
I/flutter (32713): Connection closed before full header was received
W/pool-14-thread-(32713): type=1400 audit(0.0:808179): avc: denied { search } for name="bbkcore" dev="sda17" ino=674 scontext=u:r:untrusted_app:s0:c234,c257,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0
[log] ---Xmpp Receiving:---
[log] </stream:stream>
[log] D/[Connection]: State: XmppConnectionState.Closing
I/flutter (32713): CB-SDK: CubeChatConnection: Chat connection Closing
[log] D/[Connection]: Handle secured connection done
[log] D/[Connection]: State: XmppConnectionState.Closed
I/flutter (32713): CB-SDK: CubeChatConnection: Chat connection Closed
E/flutter (32713): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: Broken pipe, errno = 32, address = chat.connectycube.com, port = 38810
E/flutter (32713): `

**Comment by TatankaConCube** [comment]
The checking `CubeSessionManager.instance.isActiveSessionValid()` returns `true` if you have valid session, but it not guarantees that you have session with user. See [our documentation](https://developers.connectycube.com/flutter/authentication-and-users?id=session-token-rights) about types of sessions.

About the last log - it has the unreadable format((( please, share logs via https://gist.github.com/ (just copy from flutter console and past there)

**Comment by Bharavi26** [comment]
@TatankaConCube sir thank you for response.
i have solved that issue.

But facing issue sometimes , opponent render not displaying.
can you please help me for that ?

when opponent screen not rendering receiving this log

`I/org.webrtc.Logging(28658): EglRenderer: Releasing.
I/org.webrtc.Logging(28658): GlShader: Deleting shader.
I/org.webrtc.Logging(28658): EglRenderer: eglBase detach and release.
D/Surface (28658): Surface::disconnect(this=0x7f5fb5c000,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) disconnect(P): api 1
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) getReleasedBuffers: returning mask 0xffffffffffffffff
D/GraphicBuffer(28658): unregister, handle(0x7f491693c0) (w:540 h:960 s:544 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f491693c0), client(109), share_fd(261)
D/GraphicBuffer(28658): unregister, handle(0x7f49169320) (w:540 h:960 s:544 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169320), client(109), share_fd(239)
D/GraphicBuffer(28658): unregister, handle(0x7f461907c0) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f461907c0), client(109), share_fd(259)
D/GraphicBuffer(28658): unregister, handle(0x7f49169500) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169500), client(109), share_fd(241)
D/Surface (28658): Surface::disconnect(this=0x7f5fb5c000,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) disconnect(P): api 1
I/org.webrtc.Logging(28658): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(28658): EglRenderer: Releasing done.
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:-1) disconnect(C)
D/GraphicBuffer(28658): unregister, handle(0x7f49169460) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169460), client(109), share_fd(264)
I/org.webrtc.Logging(28658): EglRenderer: Releasing.
I/org.webrtc.Logging(28658): EglRenderer: eglBase detach and release.
D/Surface (28658): Surface::disconnect(this=0x7f5fb5ea00,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) disconnect(P): api 1
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) getReleasedBuffers: returning mask 0xffffffffffffffff
D/Surface (28658): Surface::disconnect(this=0x7f5fb5ea00,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) disconnect(P): api 1
I/org.webrtc.Logging(28658): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(28658): EglRenderer: Releasing done.
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:-1) disconnect(C)`

**Comment by Bharavi26** [comment]
this thing is happening in demo also, i checked,
video link
https://drive.google.com/file/d/18psEd6QUfLYma9T3VmsLuqpAqsV4xTjZ/view?usp=sharing

steps for this flow in demo

login in one device. (like witho user1)

call to user2

open app in other device and login with user2

after login as soon as incoming screen apper because we are already calling from user1 from another device

after accepting call from user2

getting blank screen of opponent user in both device (call screen)

**Comment by TatankaConCube** [comment]
@Bharavi26 thank you for reporting this issue, we will investigate it

**Comment by Bharavi26** [comment]
@TatankaConCube thank you for your response,
i am waiting for your response related to this flow, please inform me whenever your investigate done on this,
because i am stuck on this and i have to complete that ASAP.

thank you

**Comment by TatankaConCube** [comment]
@Bharavi26 can you please provide the full log from the flutter console from the caller side? Please collect the full log from starting a call to ending a call without any filters. Please use https://gist.github.com/ for log sharing.

**Comment by TatankaConCube** [comment]
@Bharavi26 one more question - did you provide all required permissions (camera, mic) on the receiver side?

**Comment by Bharavi26** [comment]
yes sir i added all permission
and demo i run was downloaded which provided in doc of connectycube

**Comment by Bharavi26** [comment]
@TatankaConCube sir,
**caller and receiver log files**

[callerlog.txt](https://github.com/ConnectyCube/connectycube-flutter-samples/files/5751121/callerlog.txt)
[receiverlog.txt](https://github.com/ConnectyCube/connectycube-flutter-samples/files/5751122/receiverlog.txt)

**Comment by TatankaConCube** [comment]
@Bharavi26 please, use the latest version of our SDK (^1.1.0)
And, please, recollect logs from the receiver side, because in the provided logs I can't find signaling messages, which we send via XMPP connection.
Do I correctly understand, you provided logs during getting the error?

**Comment by Bharavi26** [comment]
Yes i provided log from starting to end of call when there is blank screen
displaying of opponent user

**Comment by Bharavi26** [comment]
ok sir let me try with 1.1.0..currently i am using 1.0.0

**Comment by Bharavi26** [comment]
[callerlog_1.1.0.txt](https://github.com/ConnectyCube/connectycube-flutter-samples/files/5753419/callerlog_1.1.0.txt)
[receiverlog_1.1.0.txt](https://github.com/ConnectyCube/connectycube-flutter-samples/files/5753420/receiverlog_1.1.0.txt)

**Comment by Bharavi26** [comment]
@TatankaConCube sir,

i think my issue is same as https://github.com/ConnectyCube/connectycube-flutter-samples/issues/49#issuecomment-745744683 this, in log which i shared there is **PeerConnection: onIceConnectionState changed to RTCIceConnectionState.RTCIceConnectionStateFailed for opponent 123....**

**Comment by TatankaConCube** [comment]
I'm studying your logs, sorry, but at this moment I don't have a solution. The main problem - I can not reproduce it on my side, yesterday I tried to do it the same as on your video, but on my side, it works as expected

**Comment by Bharavi26** [comment]
https://drive.google.com/file/d/1K5tRk3-qSOt-fJtAYMimwq6-DQkHbzH9/view?usp=sharing

@TatankaConCube sir, this code i downloaded from demo code just change sdk version as per your suggestion 1.1.0

**Comment by TatankaConCube** [comment]
@Bharavi26 It sounds strange, but I can't reproduce it with your apk, I tried about ten times with steps from your video but can't reproduce. I have some ideas for possible issues, I will try to make some improvements for SDK and share with you a test version with fixes in a few days. Will you help us to test fixes on your side?

**Comment by Bharavi26** [comment]
@TatankaConCube  sir,  thank you for your response and support.
sure sir, i'll test that.

**Comment by Bharavi26** [comment]
any update @TatankaConCube sir ?

**Comment by TatankaConCube** [comment]
@Bharavi26, sorry, we had New Year holidays, I will continue today

**Comment by TatankaConCube** [comment]
@Bharavi26 can you please test your issue in the new dev version **1.1.1-dev.1**? Just set `connectycube_sdk: 1.1.1-dev.1`, do `flutter pub get`, and rebuild your project.

**Comment by Bharavi26** [comment]
ok sir

**Comment by Bharavi26** [comment]
yes sir, its working now with 1.1.1-dev.1

**Comment by Bharavi26** [comment]
can you please update libraries version on **1.1.1-dev.1** so i can also test on my real project on which i was facing same issue

**Comment by TatankaConCube** [comment]
you can use the dev version in your project, then after publishing these changes to a stable release, you just will change the version to stable.

**Comment by Bharavi26** [comment]
sir i am already on stable -> Channel stable, 1.22.1

**Comment by TatankaConCube** [comment]
no, I meant a stable version of our SDK)))

now I'm working on upgrading dependencies to the latest versions

**Comment by TatankaConCube** [comment]
xmpp_dart lib has an issue with chat reconnection and I have to fix it first, then the author of 'xmpp_dart' should merge my PR

**Comment by TatankaConCube** [comment]
@Bharavi26 try today's version **1.1.1-dev.2** in your project. Note, don't forget to do `flutter pub get` before build.

**Comment by Bharavi26** [comment]
Thank you @TatankaConCube sir,
**1.1.1-dev.2** working with update libraries in my project...thank u for that..

can i use **1.1.1-dev.2** in my project's release build or need to wait for main conncube lib without dev.2 ?

**Comment by TatankaConCube** [comment]
@Bharavi26 yes, you can use the dev version in your project, we will release it as stable after internal checks and tests.

**Comment by TatankaConCube** [comment]
Today we released the stable version [1.1.1](https://pub.dev/packages/connectycube_sdk/versions/1.1.1). You can use it in your project.

**Comment by Bharavi26** [comment]
@TatankaConCube sir,
again same issue in ** connectycube_sdk: 1.1.1** 
connectycube_sdk: 1.1.1-dev.1 working fine but not connectycube_sdk: 1.1.1



white screen appearing in connectycube_sdk: 1.1.1

**Comment by TatankaConCube** [comment]
@Bharavi26 hmmm... it is strange... the version 1.1.1 contains all changes from 1.1.1-dev.1. Try to do `flutter clean` then `flutter pub get` then rebuild project.

**Comment by TatankaConCube** [comment]
@Bharavi26 I'm so sorry, looks there were problems with publishing version 1.1.1 to pub.dev, right now I pushed version 1.1.2, please, try it.

**Comment by Bharavi26** [comment]
@TatankaConCube sir, thank you for quick response

but that not working don't know, please look in this video which i record with version 1.1.2
https://drive.google.com/file/d/1bjtBDAIGszsA3JtkoyWg3jjxlI0b6tJE/view?usp=sharing

**Comment by TatankaConCube** [comment]
Have you do `flutter clean` and `flutter pub get` before building the app? Do you use the same version on both devices?

**Comment by TatankaConCube** [comment]
@Bharavi26 I need your logs from both sides (caller and receiver), can you provide them?

**Comment by Bharavi26** [comment]
yes sir i did clean and get...
using same version in both device

**Comment by Bharavi26** [comment]
sir...i cleared all catch sdk,project etc...
now i that type of situation not occuring...
but around 10 to 11 second white screen appearing then after video displaying

**Comment by TatankaConCube** [comment]
@Bharavi26 I need your logs from both sides (caller and receiver), can you provide them? And for me will be helpful if you provide the same log from the app which uses version 1.1.1-dev.1. Please, collect it in txt files and share them with me, as you did before.

**Comment by Bharavi26** [comment]
ok sir...i'll share that

**Comment by Bharavi26** [comment]
@TatankaConCube sir, log file link
https://drive.google.com/drive/folders/1xyxZ5Fk47IRwQOv5kHQspCHI2HyeqKrR?usp=sharing

**Comment by TatankaConCube** [comment]
No activity for a long time. Please use the latest version of our SDK for the next test. If the issue still reproduces, create a new ticket with a description. Closing...
