### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by zhukeev** [ConnectyCube/connectycube-flutter-samples#86]
**Specify the sample to which the issue belongs (use [x]):**
[X] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[ ] iOS
[X] Flutter
**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
When another user is typing getting an error

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```

flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Null check operator used on a null value
flutter:
#0      ChatImpl.parseMessage
package:xmpp_stone/…/chat/Chat.dart:51
#1      new ChatManager.<anonymous closure>
package:xmpp_stone/…/chat/ChatManager.dart:33
#2      _rootRunUnary (dart:async/zone.dart:1362:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#10     _rootRunUnary (dart:async/zone.dart:1362:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#16     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#18     _rootRunUnary (dart:async/zone.dart:1370:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#25     _rootRun (dart:async/zone.dart:1346:47)
#26     _CustomZone.run (dart:async/zone.dart:1258:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#29     _rootRun (dart:async/zone.dart:1354:13)
#30     _CustomZone.run (dart:async/zone.dart:1258:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)


flutter: ----------------------------------------------------
flutter:  TypingStatus message= 4193674
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Null check operator used on a null value
flutter:
#0      ChatImpl.parseMessage
package:xmpp_stone/…/chat/Chat.dart:51
#1      new ChatManager.<anonymous closure>
package:xmpp_stone/…/chat/ChatManager.dart:33
#2      _rootRunUnary (dart:async/zone.dart:1362:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#10     _rootRunUnary (dart:async/zone.dart:1362:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#16     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#18     _rootRunUnary (dart:async/zone.dart:1370:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#25     _rootRun (dart:async/zone.dart:1346:47)
#26     _CustomZone.run (dart:async/zone.dart:1258:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#29     _rootRun (dart:async/zone.dart:1354:13)
#30     _CustomZone.run (dart:async/zone.dart:1258:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
this crash happens inside 'xmpp_stone' lib and doesn't affect the functionality of Connectycube SDK.

**Comment by TatankaConCube** [comment]
No activity for a long time. Closing.
